org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft & Forge versions
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)

# Mappings
mapping_channel=official
mapping_version=1.20.1

# Mod metadata
mod_id=quietwalk
mod_name=Quiet Walk
mod_license=CC BY 4.0
mod_version=1.5.1
mod_group_id=com.quietwalk.mod
mod_authors=QuietWalk
mod_description=Sprint disabled. Walk=CS2 run, Ctrl=CS2 silent walk, Shift=CS2 crouch. Sneaking is silent, keeps gun pose straight, and improves TaCZ accuracy.
